version: '2'
services:
  opencommunity-app:
    image: opencommunity
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://opencommunity-mysql:3306/opencommunity?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=web_app
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://opencommunity-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://opencommunity-elasticsearch:9200
    ports:
      - 8081:8081
  opencommunity-mysql:
    extends:
      file: mysql.yml
      service: opencommunity-mysql
  opencommunity-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: opencommunity-elasticsearch
  keycloak:
    extends:
      file: keycloak.yml
      service: keycloak
